# Generated by Django 4.2.23 on 2025-07-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='lab_destination',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
