# Generated by Django 4.2.23 on 2025-07-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0002_materials_lab_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('admin', 'admin')], default='user', max_length=10),
        ),
    ]
