# Generated by Django 4.2.23 on 2025-07-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0003_alter_customusers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
