# Generated by Django 4.2.23 on 2025-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0004_alter_customusers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='lab_destination',
            field=models.CharField(blank=True, choices=[('LIPhy', 'LIPhy'), ('IGE', 'IGE')], max_length=100),
        ),
    ]
