# Generated by Django 4.2.23 on 2025-07-30 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0005_alter_materials_lab_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='date_arrivee',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
