# Generated by Django 4.2.23 on 2025-08-01 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0007_alter_materials_date_arrivee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='date_depart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
