# Generated by Django 4.2.23 on 2025-08-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0008_alter_materials_date_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='date_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
