# Generated by Django 4.2.23 on 2025-08-01 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0009_alter_materials_date_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='date_arrivee',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
