# Generated by Django 4.2.23 on 2025-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0010_alter_materials_date_arrivee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='date_arrivee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
