# Generated by Django 4.2.23 on 2025-08-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gazostheque', '0016_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
